nutrifit/homepage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    #path('myprofile/', views.principal, name='principal'),
    path('perfil/', views.perfil, name='perfil'),
    path('actualizar/', views.actualizar_perfil, name='actualizar'),
    path('cambiar_contrasenha/', views.cambiar_contrasenha, name='cambiar_contrasenha'),
    path('aux/createuser/', views.createuser, name='createuser')
]

nutrifit/nutrifit/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('rutinas/', include('exercices.urls')),
    path('nutrition/', include('nutrition.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutrifit/homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.db.models.signals import post_save

# Create your models here.
class UsuarioApp(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    sexo = models.CharField(max_length=10)
    estatura = models.IntegerField()    # Medido en cm
    peso_act = models.FloatField(max_length=5)      # Medido en kg
    peso_origen = models.FloatField(max_length=5)
    peso_des = models.FloatField(max_length=5)      # Medido en kg
    edad = models.IntegerField()
    nivel_actividad = models.CharField(max_length=25)



class Historico(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(unique=False)
    tdee = models.FloatField(max_length=15, unique=False) # Calorías diarias consumidas en total (TDEE en inglés). Medido en Kcal/day
    peso = models.FloatField(max_length=5)



class Historico_micronutrientes(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True, unique=False)
    calcium = models.FloatField(max_length=6, unique=False)    # Medido en mg/d
    chromium = models.FloatField(max_length=5, unique=False)   # Medido en μg/d
    copper = models.FloatField(max_length=5, unique=False)     # Medido en μg/d
    fluoride = models.FloatField(max_length=5, unique=False)   # Medido en mg/d
    iodine = models.FloatField(max_length=4, unique=False)     # Medido en μg/d
    iron = models.FloatField(max_length=4, unique=False)       # Medido en mg/d
    magnesium = models.FloatField(max_length=5, unique=False)  # Medido en mg/d
    manganese = models.FloatField(max_length=4, unique=False)  # Medido en mg/d
    molybdenum = models.FloatField(max_length=4, unique=False) # Medido en μg/d
    phosphorus = models.FloatField(max_length=5, unique=False) # Medido en mg/d
    selenium = models.FloatField(max_length=4, unique=False)   # Medido en μg/d
    zinc = models.FloatField(max_length=4, unique=False)       # Medido en mg/d
    potassium = models.FloatField(max_length=6, unique=False)  # Medido en mg/d
    sodium = models.FloatField(max_length=6, unique=False)     # Medido en mg/d
    chloride = models.FloatField(max_length=6, unique=False)   # Medido en g/d

nutrifit/homepage/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from crispy_forms.layout import Submit, Layout, ButtonHolder
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.core.exceptions import ValidationError  
from homepage.models import UsuarioApp, Historico, Historico_micronutrientes
from homepage.apis.health import *
from threading import Thread
from django.utils import timezone


class UserRegisteredForms(UserCreationForm):
    SEX_CHOICES = (
        ('male', 'Masculino'),
        ('female', 'Femenino')
    )

    nivel_actividad_opciones = (
        ('sedentary', 'Sedentario'),
        ('light exercise', 'Bajo'),
        ('moderate exercise', 'Medio'),
        ('hard exercise', 'Alto'),
        ('professional athlete','Atleta profesional')
    )
    username = forms.CharField(label="Usuario", min_length=4, max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Usuario', 'class': 'form-control'}))
    password1 = forms.CharField(label='Contraseña', min_length=8,widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña', 'class': 'form-control'}))
    password2 = forms.CharField(label='Confirma contraseña', min_length=8,widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar contraseña', 'class': 'form-control'}),)
    email = forms.EmailField(label='Correo',widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    sexo = forms.ChoiceField(label='Sexo', choices=SEX_CHOICES, widget=forms.RadioSelect)
    estatura = forms.FloatField(label='Estatura(cm)', min_value=0, max_value=240,widget=forms.NumberInput(attrs={'placeholder': 'Estatura', 'style': 'width: 150px;','class': 'form-control'}))
    peso_deseado = forms.FloatField(label='Peso deseado(kg)', min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Peso deseado', 'style': 'width: 150px;','class': 'form-control'}))
    peso_actual = forms.FloatField(label='Peso actual(kg)', min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Peso actual', 'style': 'width: 150px;','class': 'form-control'}))
    edad = forms.IntegerField(label="Edad", min_value=0, widget=forms.NumberInput(attrs={'class':'form-control'}))
    nivel_actividad = forms.ChoiceField(label="Nivel de actividad fisico", choices=nivel_actividad_opciones, widget=forms.RadioSelect)
    

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'sexo', 'edad', 'estatura', 'peso_actual', 'peso_deseado', 'nivel_actividad']
        help_texts = {k:"" for k in fields}
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()  
        if UsuarioApp.objects.filter(email=email).exists():
            raise ValidationError('El email ya existe')
        return email
    
    def save(self, commit = True):  

        user = User.objects.create_user(  
            username=self.cleaned_data['username'],    
            password=self.cleaned_data['password1'],
            email = self.cleaned_data['email']
        )

        sexo_cleaned = self.cleaned_data['sexo']
        edad_cleaned = self.data['edad']
        estatura_cleaned = self.data['estatura']
        peso_act_cleaned = self.data['peso_actual']
        peso_des_cleaned = self.data['peso_deseado']
        nivel_actividad_cleaned = self.cleaned_data['nivel_actividad']

        uapp = UsuarioApp(user = user, email = self.cleaned_data['email'], sexo = sexo_cleaned, edad = int(edad_cleaned), estatura = int(estatura_cleaned), peso_act = float(peso_act_cleaned), peso_des = float(peso_des_cleaned), peso_origen=float(peso_act_cleaned), nivel_actividad = nivel_actividad_cleaned)
        uapp.save()

        #micronutrientes = get_micronutrients(sexo_cleaned[0], int(edad_cleaned[0]))
        t = Thread(target=self._save_micronutrients, args=[sexo_cleaned, int(edad_cleaned), user])
        t.setDaemon(True)
        t.start()

        historico = Historico(user = user, date=timezone.now(), tdee = get_tdee(int(estatura_cleaned), float(peso_act_cleaned), sexo_cleaned, int(edad_cleaned), nivel_actividad_cleaned), peso = float(peso_act_cleaned))
        #historico_mic = Historico_micronutrientes(user = user, calcium = micronutrientes['calcium'], chromium = micronutrientes['chromium'], copper = micronutrientes['copper'], fluoride = micronutrientes['fluoride'], iodine = micronutrientes['iodine'], iron = micronutrientes['iron'], magnesium = micronutrientes['magnesium'], manganese = micronutrientes['manganese'], molybdenum = micronutrientes['molybdenum'], phosphorus = micronutrientes['phosphorus'], selenium = micronutrientes['selenium'], zinc = micronutrientes['zinc'],potassium = micronutrientes['potassium'], sodium = micronutrientes['sodium'],chloride = micronutrientes['chloride'])

        historico.save()
        #historico_mic.save()

        return user
    
    def _save_micronutrients(self, sexo, edad, user):
        micronutrientes = get_micronutrients(sexo, edad)
        historico_mic = Historico_micronutrientes(user = user, calcium = micronutrientes['calcium'], chromium = micronutrientes['chromium'], copper = micronutrientes['copper'], fluoride = micronutrientes['fluoride'], iodine = micronutrientes['iodine'], iron = micronutrientes['iron'], magnesium = micronutrientes['magnesium'], manganese = micronutrientes['manganese'], molybdenum = micronutrientes['molybdenum'], phosphorus = micronutrientes['phosphorus'], selenium = micronutrientes['selenium'], zinc = micronutrientes['zinc'],potassium = micronutrientes['potassium'], sodium = micronutrientes['sodium'],chloride = micronutrientes['chloride'])
        historico_mic.save()
    
    def get_username(self):
        return self.cleaned_data['username']
    
    def get_passwd(self):
        return self.cleaned_data['password1']
        

class UserLoginForms(forms.Form):
    
    correo = forms.EmailField(label='Correo', widget=forms.EmailInput)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['correo', 'password']
        help_texts = {k:"" for k in fields}


class EditProfileForm(UserChangeForm):
    password = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'type': 'hidden'}))
    
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Nombre de usuario'
        self.fields['username'].widget.attrs['label'] = 'Nombre de usuario'

    
class ExtraProfileForm(forms.ModelForm):

    SEX_CHOICES = (
        ('male', 'Masculino'),
        ('female', 'Femenino')
    )

    nivel_actividad_opciones = (
        ('sedentary', 'Sedentario'),
        ('light exercise', 'Bajo'),
        ('moderate exercise', 'Medio'),
        ('hard exercise', 'Alto'),
        ('professional athlete','Atleta profesional')
    )

    email = forms.EmailField(label='Correo',widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    sexo = forms.ChoiceField(label='Sexo', choices=SEX_CHOICES, widget=forms.RadioSelect)
    estatura = forms.FloatField(label='Estatura(cm)', min_value=0, max_value=240,widget=forms.NumberInput(attrs={'placeholder': 'Estatura', 'style': 'width: 150px;','class': 'form-control'}))
    peso_des = forms.FloatField(label='Peso deseado(kg)', min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Peso deseado', 'style': 'width: 150px;','class': 'form-control'}))
    peso_act = forms.FloatField(label='Peso actual(kg)', min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Peso actual', 'style': 'width: 150px;','class': 'form-control'}))
    edad = forms.IntegerField(label="Edad", min_value=0, widget=forms.NumberInput(attrs={'class':'form-control'}))
    nivel_actividad = forms.ChoiceField(label="Nivel de actividad fisico", choices=nivel_actividad_opciones, widget=forms.RadioSelect)

    class Meta:
        model = UsuarioApp
        fields = ('email', 'sexo', 'estatura', 'edad', 'peso_act', 'peso_des', 'nivel_actividad')



class NuevoPeso(forms.ModelForm):
    peso_act = forms.FloatField(label="", min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Actualizar peso (kg)','style': 'width: 200px; margin: auto;','class': 'form-control'}))

    class Meta:
        model = UsuarioApp
        fields = ('peso_act', )

class RangoFecha(forms.Form):
     
    desde = forms.DateField(
        label = "Desde",
        #required = True,
        widget = forms.DateInput(format="$b %d, %Y", attrs={"type": "date", 'style': 'width: 175px; margin: auto;', 'class':'form-control col'}),
        input_formats=["$b %d, %Y"]
    )
       
    hasta = forms.DateField(
        label = "Hasta",
        #required = True,
        widget = forms.DateInput(format="$b %d, %Y", attrs={"type": "date", 'style': 'width: 175px; margin: auto;','class':'form-control col-auto'}),
        input_formats=["$b %d, %Y"]
    )

    def __init__(self, *args, **kwargs):
        initial = kwargs.pop('initial', None)
        super(RangoFecha, self).__init__(*args, **kwargs)
        if initial:
            self.fields['desde'].widget.attrs['value'] = initial['desde']
            self.fields['hasta'].widget.attrs['value'] = initial['hasta']
    

    
    
    

    

nutrifit/homepage/templates/home/barra_base.html
{% load static %}
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <a class="navbar-brand p-2" href="{% url 'home' %}">
      <h1 class="display-3" style="font-size: 40px; margin-bottom: -5px">Nutrifit <img src="{% static 'media/nutrifit.png' %}" alt="Logo" width="40px" style="margin-bottom: 5px"></h1>
      </a>

    {% if user.is_authenticated %}
    <div class="me-auto">
      <div class="d-inline-flex align-items-center">
        <a id="ocultar" class="btn" href="{% url 'misrutinas' %}"><h5 class="display-5">Físico</h5></a>
        <a id="ocultar" class="btn" href="{% url 'recipesearch' %}"><h5 class="display-5">Nutrición</h5></a>
      </div>
    </div>  

    <a class="navbar-brand" type="button" id="boton-nav" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <img src="{% static 'media/usuario.png' %}" width="75px" style="border: 5px solid yellowgreen;" height="75px" alt="imagen de perfil" class="rounded-circle">
    </a>
    
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title display-5" id="offcanvasNavbarLabel"><b style="color: hsl(271, 76%, 53%);">{{ user.username }}</b></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'perfil' %}">Mi perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'misrutinas' %}">Físico</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'recipesearch' %}">Nutrición</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Cerrar sesión</a>
          </li>
        </ul>
      </div>
    </div>
    {% else %}
    <div>
      <a class="btn btn-secondary btn-lg" id="registrarse" style="margin-left: 10px;" href="{% url 'register' %}" role="button">Registrate</a>
      <a class="btn btn-primary btn-lg" id="login" style="margin-left: 10px;" href="{% url 'login' %}" role="button">Login</a>
    </div>
    {% endif %}
  </div>
</nav>


<style>
  #ocultar{
    background-color: hsl(271, 76%, 53%);
    color: white; 
    font-weight: bold; 
    margin-left: 30px; 
    font-size: 18px; 
    padding: 10px 20px;
  }

  #ocultar:hover {
    background-color: hsl(271, 68%, 36%);
    color: white; 
    font-weight: bold; 
    margin-left: 30px; 
    font-size: 18px; 
    padding: 10px 20px;
  }
  
  .navbar-custom {
    background-color: hsl(271, 76%, 53%);
  }

  .navbar-custom .navbar-brand,
  .navbar-custom .navbar-text {
    color: white;
  }

  .nav-item:hover{
      background-color: aliceblue;
    }

  @media screen and (max-width: 767px) {
    #ocultar{
      display: none;
    }
    .navbar-brand h1 {  
      font-size: 150% !important; 
      margin-right: 0px;
    }   
    
    .nav-link.btn {
      margin-left: -10px !important; 
      font-size: 9px !important;
      padding: 2px 6px !important;
    }
    .navbar-brand img {
      width: 30px;
      height: 30px;
    }
    .rounded-circle {
      width: 60px !important; 
      height: 60px !important; 
    }
  }
</style>

<script>
  function ajustarTamagno(){
    var screenWidth = window.innerWidth
    var registrarse = document.getElementById("registrarse");
    var login = document.getElementById("login");

    if (screenWidth <= 767){
      registrarse.classList.remove("btn-lg");
      login.classList.remove("btn-lg");
    }
    else{
      registrarse.classList.add("btn-lg");
      login.classList.add("btn-lg")
    }
  }
  window.onload = ajustarTamagno;
  window.onresize = ajustarTamagno;
</script>

nutrifit/homepage/templates/home/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Pantalla Principal</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  
</head>
<body>
  {% include 'home/barra_base.html' %}
  {% include 'home/messages.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <br><br><br>
</body>
</html>

nutrifit/homepage/templates/home/cambiar_contrasenha.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h2 class="text-center">Cambiar contraseña</h2>
    <form method="POST" action="{% url 'cambiar_contrasenha' %}">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <p>Your form has errors</p>
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="Cambiar contraseña" class="btn btn-secondary">
    </form>
</div>

{% endblock %}

nutrifit/homepage/templates/home/editar_perfil.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
  <br><br>  
  <div class="text-center">
    <img src="{% static 'media/usuario.png' %}" alt="imagen usuario" width="250px" class="rounded-circle" id="nav-image">
  </div>
  <br>

  <form method="POST" action="{% url 'actualizar' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <p>Hay errores en el formulario:</p>
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {{ user_form.as_p }}
    <p>Contraseña: ****** <small><a href="{% url 'cambiar_contrasenha' %}">Cambiar contraseña</a></small></p>
    {{ profile_form.as_p }}

    <input type="submit" value="Actualizar" class="btn btn-success">


  </form>

{% endblock %}

nutrifit/homepage/templates/home/inicio_sesion.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="col-md-6 offset-md-3">
    <br><br><br>
    <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
          <div class="mb-3">
           <br>
            <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter email" name="email">
          </div>
          <div class="mb-3">
            <input type="password" class="form-control" name="password" placeholder="Enter password">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
    
{% endblock %}

nutrifit/homepage/templates/home/messages.html
{% if messages %}
    <div class="col col-md-2" id="list-messages">
    {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" id="message" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
    {% endfor %}
    </div>
{% endif %}


<style>
    .alert{

    }
    #message{
        margin-bottom: 20px
    }
    #list-messages{
        position: absolute;
        margin-left: 75%;
        margin-top: 20px;
    }
    @media (max-width: 767px) {
        #list-messages{
            margin-left: 50%;
        }
        .alert {
            right: calc(50% - 45%);
            left: auto;
        }
    }
</style>

nutrifit/homepage/templates/home/perfil.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
  <br><br>  
  <div class="text-center">
    <img src="{% static 'media/usuario.png' %}" alt="imagen usuario" width="250px" class="rounded-circle" id="nav-image">
  </div>
    <h2>Nombre usuario: {{ datos_usuario.user.username}}</h2>
    <h2>Email: {{datos_usuario.email}}</h2>
    <h2>Estatura: {{datos_usuario.estatura}} (cm)</h2>
    <h2>Sexo: {{datos_usuario.sexo}}</h2>
    <h2>Edad: {{datos_usuario.edad}} Años</h2>
    <h2>Nivel actividad: {{datos_usuario.nivel_actividad}}</h2>
    <h2>Peso actual: {{datos_usuario.peso_act}}</h2>
    <h2>Peso deseado: {{datos_usuario.peso_des}}</h2>
    <a class="btn btn-primary" role="button" href="{% url 'actualizar' %}">Editar</a>
{% endblock %}

nutrifit/homepage/templates/home/registro.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<br>
<h1 class="d-flex justify-content-center">PANTALLA REGISTRO DEL USUARIO</h1>
  <br>
<div class="d-flex justify-content-center align-items-center">
  <img  src="{% static 'media/logo_registro.jpg' %}" width="100" height="100">
</div>
<br>
<div class="col-md-6 offset-md-3">
  <form method="POST" action="{% url 'register' %}">
    {% csrf_token %}
      {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          <p>El formulario tiene errores</p>
          {% for field in form %}
            {% if field.errors %}
              {{ field.errors }}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      {{ form.as_p }}
      <input type="submit" value="Registrarse" class="btn btn-secondary">

  </form>

</div>

<!--
<br>
<h1 style="text-align: center;"> PANTALLA REGISTRO DEL USUARIO</h1>
<br>
<div style="text-align: center;" class="container center">
  <img src="/nutrifit/homepage/static/media/logo_registro.jpg" width="100" height="100">
  <form method="POST" action="{% url 'register' %}">
    {{form.as_p}}
    <input type="submit" value="Registrarse" class="btn btn-secondary">
  </form>
  <form class="form" id="username-input" method="post" style="text-align: center;">
    <div class="form-container">
      <div class="form-column">
        <div class="form-row">
          <label for="id_username">Nombre de usuario:</label>
          {{ form.username }}
        </div>
        <div class="form-row">
          <label for="id_password1">Contraseña:</label>
          {{ form.password1 }}
        </div>
        <div class="form-row">
          <label for="id_password2">Confirmar contraseña:</label>
          {{ form.password2 }}
        </div>
        <div class="form-row">
          <label for="id_correo">Correo:</label>
          {{ form.correo }}
        </div>
      </div>
      <div class="form-column">
        <div class="form-row">
          <label for="id_sexo">Sexo:</label>
          {{ form.sexo }}
        </div>
        <div class="form-row">
          <label for="id_estatura">Estatura:</label>
          {{ form.estatura }}
        </div>
        <div class="form-row">
          <label for="id_peso_deseado">Peso deseado:</label>
          {{ form.peso_deseado }}
        </div>
        <div class="form-row">
          <label for="id_peso_actual">Peso actual:</label>
          {{ form.peso_actual }}
        </div>
      </div>
  </div>
  </form>
  
<br>
<br>
<form  action="{% url 'login' %}" method="get" style="text-align: center;">
  <button type="submit" style=" font-size: 20px; margin-left: 20px;  width: 400px; height: 35px;"><b>YA TIENES CUENTA</b></button>
</form>-->
{% endblock %}